### ISSUE TITLE
Make position service run as a foreground service

### ISSUE THREAD

**Issue by maks** [ubx/SkyLinesTracker#17]
Thanks for writing this great app! I had in mind to write exactly the same sort of app.

One thing I noticed is that you don't run the service as a foreground service which makes it more likely that the OS could decide to stop it while its running in the background, especially on some OEMs customised versions of Android which have quite aggressive power management. 

An added benefit would also be that the user would have a ongoing notification informing them that the tracker is running in the background and an quick way to get to the main activity to stop tracking if required.

I implemented this in my app, its only a small amount of code: https://github.com/maks/UartBridge/blob/master/app/src/main/java/com/manichord/uartbridge/UsbService.java#L242
and you're welcome to use it or any other bits of code that might be helpful from it as its under an MIT license.

**Comment by ubx** [comment]
Fixed anyway. Version 1.3.3
