### ISSUE TITLE
Tracking not showing on SkyLines

### ISSUE THREAD

**Issue by kapitan-iglu** [ubx/SkyLinesTracker#28]
Few days ago skylines.aero [was down because of static IP change](https://github.com/skylines-project/skylines/issues/1907#issuecomment-696222658). App was working well before outage. But now tracking using this app is not working anymore. App is up, GPS is OK, queue is 0sec, but on skylines live tracking list I'm still missing...

Maybe the problem is on skylines site, I don't know. Could you please check app side?

Tracking from XCSoar is not working too, but I assume it is [because of hardcoded IP](https://github.com/XCSoar/XCSoar/pull/478) inside it. I see that in last version of app change from IP to DNS was made, so another IP change should't be problem for app.

I'm using App Version: 1.4.3

**Comment by ubx** [comment]
Version 1.4.3 of SkylinesTracker uses DNS (skylines.aero). I also tried the last version of XCSoar (version 6.8.17-Android) today, but it doesn't work either.  The problem is probably on skylines site ?
