### ISSUE TITLE
Issue when re-opening the notification from the notification

### ISSUE THREAD

**Issue by vicb** [ubx/SkyLinesTracker#30]
Hey,

When I launch the app switch to some other app and come back by clicking on the launcher icon everything works as expected.

Now if you re-open/focus the app by clicking on the system notification ("Running in the background") then a new "activity"? is created each time. As an example if you tap the notification 3 times then you have to exit the app 4 times to really exit the app (the initial launch + the 3 activities created by tapping the notification).

I hope it's clear enough. Please ask me any other question otherwise.

version 1.4.5, Android 12. pixel 6.

Thanks for this great app.

**Comment by ubx** [comment]
Fixed in 23b8d21f56510c7a51925c62856c966b1c51d03e.

Tested with Android 12, with Android emulator, but not with real hardware. Please close if it is okay.

**Comment by vicb** [comment]
It works great, thanks for fixing this quickly.

I seem to remember that i saw you name on flyxc, your based on Australia,
right ?
