### ISSUE TITLE
Problem with app on pixel6a and android 14

### ISSUE THREAD

**Issue by nokkerlcad** [ubx/SkyLinesTracker#31]
App stalls when on switch is used on android 14 update.

2 affected phones known.

**Comment by ubx** [comment]
I was able to reproduce the problem on the emulator and will investigate it further shortly.

**Comment by nokkerlcad** [comment]
Awesome, thank you so much!

**Comment by ubx** [comment]
If you think the problem is fixed, please close the issue.

**Comment by nokkerlcad** [comment]
Working now, thanks !!!

**Comment by ubx** [comment]
Fixed in 4fb162276cc7633448db159ff08c7d753b552e18, app version 1.4.8.
